A few improvements - Add support for local config dir (~/.customizepkg) - Support unquoted values e.g. depends=(aaa bbb ccc) - Tidy up read function - Better explanation of action on remove/replace - Removed unnecessary space on "add"

diff --git a/customizepkg b/customizepkg
--- a/customizepkg
+++ b/customizepkg
@@ -14,6 +14,7 @@
 
 NAME=`basename $0`
 CONFIGDIR="/etc/$NAME.d"
+LOCALCONFIGDIR="$HOME/.$NAME"
 
 usage() {
    echo "Without any option, $NAME read PKGBUILD in current directory and show a diff between original PKGBUILD and customized PKGBUILD."
@@ -36,32 +37,29 @@ modify_file()
 	configfile=$1
 	originalscriptfile=$2
 	scriptfile=$3
+
 	grep --invert-match "\(^#\|^$\)" $configfile |
-	while read line; do
-		unset action context pattern value
-		action=$(echo $line | awk -F# '{ print $1 }')
-		context=$(echo $line | awk -F# '{ print $2 }')
-		pattern=$(echo $line | awk -F# '{ print $3 }')
+	while IFS='#' read -r action context pattern value; do
 		case $action in
 			remove|replace)
-				value=`echo $line | awk -F [^#]# '{print $4}'`
-				echo "=> removes/replaces '$pattern' by '$value' in $context"
+				[[ $action == remove ]] && echo "=> removes '$pattern' in $context" || echo "=> replaces '$pattern' with '$value' in $context"
 				if [ "$action" = "replace" -a "$context" != "global" ]; then
 					value="$(echo $value | tr -d "\'")"
 				fi
 				if [ "$context" = "global" ]; then
 					sed -i "s+$pattern+$value+g" "$scriptfile"
 				else
-					pattern="$pattern[<>=]*[a-z0-9.{$}]*"
+					pattern="$pattern[<>=]*[a-z0-9.{$}]*[' ]"
 					if [ "$action" = "replace" ]; then
 						sed -i "/^$context=/,/)$/ s+$pattern+$value+g" "$scriptfile"
 					else
-						sed -i "/^$context=/,/)$/ s+['\"][[:blank:]]*\b$pattern[[:blank:]]*['\"]+$value+g" "$scriptfile"
+						sed -i "/^$context=/,/)$/ s+[[:blank:]]*[']*${pattern}[']*+$value +g" "$scriptfile"
+						#sed -i "/^$context=/,/)$/ s+[[:blank:]]*[']${pattern}[']+$value+g" "$scriptfile"
 					fi
 				fi
 				;;
 			add)
-				value=" \"$(echo $pattern | tr -d "\'")\""
+				value="'$(echo $pattern | tr -d "\'")'"
 				echo "=> adds $value in $context"
 				# add the full line if it doesn't exist or just the value
 				if grep --quiet "^$context=" "$scriptfile"; then
@@ -71,7 +69,7 @@ modify_file()
 				fi
 				;;
 			*)
-				echo "error: unknow action '$action'"
+				echo "error: unknown action '$action'"
 				;;
 		esac
 	done
@@ -113,11 +111,13 @@ source ./PKGBUILD.pkgname 2> /dev/null
 
 for package in "${pkgname[@]}"
 do
-	if [ ! -r "$CONFIGDIR/$package" ]; then
-		echo "no configuration found for $package in $CONFIGDIR/"
-		continue
+	if [ -r "$LOCALCONFIGDIR/$package" ]; then
+		cp $LOCALCONFIGDIR/$package ./$package.customize
+	elif [ -r "$CONFIGDIR/$package" ]; then
+		cp $CONFIGDIR/$package ./$package.customize
 	else
-		cp $CONFIGDIR/$package  ./$package.customize
+		echo "no configuration found for $package in $LOCALCONFIGDIR/ or $CONFIGDIR/"
+		continue
 	fi
 
 	#adding new files current dir from  $CONFIGDIR/$package folder and including them to PKGBUILD
